### ISSUE TITLE
Cookbook converge fails in newest Chef 16.5

### ISSUE THREAD

**Issue by djessich** [criteo-cookbooks/nexus3#118]
### Problem Statement
Converging this cookbook using Chef 16.5.64 (stable release) fails due to `Nexus API: 'uninitialized constant Addressable::URI'` error.

### Environment
nexus3 Cookbook: 3.6.0
Chef Client 16.5.64
Test Kitchen: 2.5.4
Platform: Centos 7+ (Kitchen VM)

### Chef Client Error

```
* ruby_block[block until Nexus default@8081 operational] action run/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
/opt/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:22: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
      - execute the ruby block block until Nexus default@8081 operational
    * nexus3_api[admin_change_password for default@8081] action create
      
      ================================================================================
      Error executing action `create` on resource 'nexus3_api[admin_change_password for default@8081]'
      ================================================================================
      
      RuntimeError
      ------------
      Nexus API: 'uninitialized constant Addressable::URI' 
      
      Cookbook Trace: (most recent call first)
      ----------------------------------------
      /opt/kitchen/cache/cookbooks/nexus3/libraries/api.rb:58:in `rescue in request'
      /opt/kitchen/cache/cookbooks/nexus3/libraries/api.rb:56:in `request'
      /opt/kitchen/cache/cookbooks/nexus3/resources/api.rb:8:in `block in class_from_file'
      
      Resource Declaration:
      ---------------------
      # In /opt/kitchen/cache/cookbooks/nexus3/resources/default.rb
      
      127:   nexus3_api pwchanger do
      128:     script_name 'change_admin_password'
      129:     content "security.securitySystem.changePassword('admin', args)"
      130:     args new_resource.nexus3_password
      131:     api_client lazy { ::Nexus3::Api.local(port, 'admin', ::File.read(passwd_file)) }
      132:     only_if { ::File.exist? passwd_file }
      133:     action :nothing
      134:     notifies :delete, "file[#{passwd_file}]"
      135:   end
      136: 
      
      Compiled Resource:
      ------------------
      # Declared in /opt/kitchen/cache/cookbooks/nexus3/resources/default.rb:127:in `block in class_from_file'
     
      nexus3_api("admin_change_password for default@8081") do
        action [:nothing]
        default_guard_interpreter :default
        declared_type :nexus3_api
        cookbook_name "server-infrastructure-nexus"
        api_client #<Nexus3::Api:0x00000000043d0fa0 @endpoint="http://localhost:8081/service/rest/v1/script/", @password="2a0d31fc-ee36-4fc9-80de-96d8f3870cc7", @user="admin">
        content "security.securitySystem.changePassword('admin', args)"
        args "secret"
        script_name "change_admin_password"
        only_if { #code block }
      end

      System Info:
      ------------
      chef_version=16.5.64
      platform=centos
      platform_version=7.8.2003
      ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
      program_name=/opt/chef/bin/chef-client
      executable=/opt/chef/bin/chef-client
```

### Reproduction
Converge a Kitchen VM with Chef Client 16.5.64. The default recipe of this cookbook, should be in the test nodes run_list. No additional configuration for this cookbook should be required, to reproduce the issue.

### Possible Workarounds:
Currently none for the author.

**Comment by Annih** [comment]
Thanks for this report @djessich 
This has already been addressed in #110 however we still need to release a new version of the cookbook.
Would you be able to test against *master* branch?

**Comment by djessich** [comment]
@Annih I tested using the unreleased master branch and I could successfully install Nexus 3. However the following warning will be printed:

```
* ruby_block[block until Nexus default@8081 operational] action run
  - execute the ruby block block until Nexus default@8081 operational
* nexus3_api[admin_change_password for default@8081] action create[2020-10-01T23:23:02+00:00] WARN: A 'Nexus3::ApiError' occured: HTTP_STATUS=404 

  - create admin@http://localhost:8081/service/rest/v1/script/
  -   set content    to "security.securitySystem.changePassword('admin', args)"
  -   set api_client to #<Nexus3::Api:0x0000000003fee4f0 @endpoint=http://localhost:8081/service/rest/v1/script/, @user=admin>
* nexus3_api[admin_change_password for default@8081] action run
  - running script change_admin_password
[2020-10-01T23:23:03+00:00] WARN: A 'Nexus3::ApiError' occured: HTTP_STATUS=401
```

I do not know if this may be a problem in the future. However, the installation works :+1:

**Comment by djessich** [comment]
BTW: On master branch it does not work to create repositories anymore. See stacktrace below:
```
* nexus3_api[upsert_repo archives-ant] action run
  
================================================================================
Error executing action `run` on resource 'nexus3_api[upsert_repo archives-ant]'
================================================================================

Nexus3::ApiError
----------------
HTTP_STATUS=400 {
  "name" : "upsert_repo",
  "result" : "javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl$$EnhancerByGuice$$6b7b8b8d.newConfiguration() is applicable for argument types: () values: []"
}

Cookbook Trace: (most recent call first)
----------------------------------------
/opt/kitchen/cache/cookbooks/nexus3/libraries/api.rb:67:in `request'
/opt/kitchen/cache/cookbooks/nexus3/libraries/api.rb:72:in `run_script'
/opt/kitchen/cache/cookbooks/nexus3/resources/api.rb:26:in `block (2 levels) in class_from_file'
/opt/kitchen/cache/cookbooks/nexus3/resources/api.rb:25:in `block in class_from_file'

Resource Declaration:
---------------------
# In /opt/kitchen/cache/cookbooks/nexus3/resources/repo.rb

28:     nexus3_api "upsert_repo #{new_resource.repo_name}" do
29:       script_name 'upsert_repo'
30:       args name: new_resource.repo_name,
31:            type: new_resource.repo_type,
32:            online: new_resource.online,
33:            attributes: new_resource.attributes,
34:            multi_policy_cleanup_support: Gem::Version.new(node['nexus3']['version'].split('-').first) >=
35:                                          Gem::Version.new('3.19.0')
36: 
37:       action %i[create run]
38:       api_client new_resource.api_client
39: 
40:       content ::Nexus3::Scripts.groovy_content('upsert_repo', node)
41:     end
42:   end
```

**Comment by djessich** [comment]
Can be closed. Works with current master on Chef 16.5+.
