### ISSUE TITLE
Cant seem to start the service

### ISSUE THREAD

**Issue by awolde** [criteo-cookbooks/nexus3#51]
I've been trying to converge this cookbook on test kitchen. I increased the vm memory to 4gig. Here's my recipe.
```
node.default['java']['jdk_version'] = '8'
include_recipe 'java'

nexus3 'nexus' do
  properties_variables(
    host: '0.0.0.0',
    port: '8443',
    context_path: '/components/'
  )
  action :install
end
```

And this the chef error I get

```
- enable service service[nexus3_nexus]

           * ruby_block[block until operational] action nothing (skipped due to action :nothing)
           * nexus3_service_systemd[nexus] action restart
             * service[nexus3_nexus] action restart
        - restart service service[nexus3_nexus]

           * ruby_block[block until operational] action run

             ================================================================================
             Error executing action `run` on resource 'ruby_block[block until operational]'
             ================================================================================

             NoMethodError
             -------------
             undefined method `nexus_timeout' for Custom resource nexus3 from cookbook nexus3

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:38:in `rescue in wait_until_ready!'
             /tmp/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:20:in `wait_until_ready!'
             /tmp/kitchen/cache/cookbooks/nexus3/resources/default.rb:105:in `block (3 levels) in class_from_file'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/nexus3/resources/default.rb

             102:   ruby_block 'block until operational' do
             103:     block do
             104:       Chef::Log.info "Waiting until Nexus is listening on port #{node['nexus3']['properties_variables']['port']}"
             105:       wait_until_ready!(node['nexus3']['api']['endpoint'], node['nexus3']['api']['wait'])
             106:     end
             107:     action :nothing
             108:   end
             109: end

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/nexus3/resources/default.rb:102:in `block in class_from_file'

             ruby_block("block until operational") do
        action [:nothing]
        default_guard_interpreter :default
        block_name "block until operational"
        declared_type :ruby_block
        cookbook_name "role_nexus"
        block #<Proc:0x00000000022188e0@/tmp/kitchen/cache/cookbooks/nexus3/resources/default.rb:103>
             end

             System Info:
             ------------
             chef_version=13.6.4
             platform=ubuntu
             platform_version=16.04
             ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
             program_name=chef-client worker: ppid=2298;start=15:51:20;
             executable=/opt/chef/bin/chef-client


           ================================================================================
           Error executing action `install` on resource 'nexus3[nexus]'
           ================================================================================

           NoMethodError
           -------------
           ruby_block[block until operational] (/tmp/kitchen/cache/cookbooks/nexus3/resources/default.rb line 102) had an error: NoMethodError: undefined method `nexus_timeout' for Custom resource nexus3 from cookbook nexus3

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:38:in `rescue in wait_until_ready!'
           /tmp/kitchen/cache/cookbooks/nexus3/libraries/nexus_helper.rb:20:in `wait_until_ready!'
           /tmp/kitchen/cache/cookbooks/nexus3/resources/default.rb:105:in `block (3 levels) in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/role_nexus/recipes/default.rb

            27: nexus3 'nexus' do
            28:   properties_variables(
            29:     host: '0.0.0.0',
            30:     port: '8443',
            31:     context_path: '/components/'
            32:   )
            33:   action :install
            34: end
            35:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/role_nexus/recipes/default.rb:27:in `from_file'

           nexus3("nexus") do
             action [:install]
             updated true
             updated_by_last_action true
             default_guard_interpreter :default
             declared_type :nexus3
             cookbook_name "role_nexus"
             recipe_name "default"
             properties_variables {:host=>"0.0.0.0", :port=>"8443", :context_path=>"/components/"}
             instance_name "nexus"
             service_name "nexus"
             vmoptions_variables {"Xms"=>"1200M", "Xmx"=>"1200M"}
           end

           System Info:
           ------------
           chef_version=13.6.4
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=2298;start=15:51:20;
           executable=/opt/chef/bin/chef-client


       Running handlers:
```

**Comment by olive42** [comment]
You are right, there is a bug. However you might want to check why your service is not starting in the Kitchen test (kitchen login, check logs)
